export type CreateOrderDto = {
  from_address_geocoder: string;
  to_address_geocoder: string;
  from_address: string;
  from_latitude: number;
  from_longitude: number;
  to_address: string;
  to_latitude: number;
  to_longitude: number;
  h3_hexagon_id: string;
  phone_user: string;
  name_user: string;
  tip: number;
  total: number;
  discount: number;
  city_id: number;
  merchant_id: number;
  paymentModeId: number;
  userId: number;
  coverageId: number;
  details: DetailCreateOrderDto[];
  comment?: string;
  orderProvider: string;
  providerId?: string;
  tipOriginal: number;
  createdAt?: string;
  currency: string;
  baseCost?: number;
  extraCost?: number;
  vehicleTypeId: number;
  storeName: string;
  isPickup: number;
  point?: number;
  isTest?: number;
  subProvider?: string;
  providerImage?: string;
  nit?: string;
  businessName?: string;
};

export type DetailCreateOrderDto = {
  quantity: number;
  productId: number;
  price: number;
  notes?: string;
  toppings?: {
    quantity: number;
    toppingId: number;
    toppingName: string;
    subToppingId: number;
    subToppingName: string;
    price: number;
  }[];
  subtotal?: number;
};
